language: java
sudo: true

before_install:
  - sudo apt-get -qq update
  - sudo sudo apt install tor torsocks whois 
  - sudo sed -i 's/#ControlPort 9051/ControlPort 9051/g' /etc/tor/torrc
  - sudo sed -i 's/#CookieAuthentication 0/CookieAuthentication 0/g' /etc/tor/torrc
  - sudo /etc/init.d/tor restart
  - torify whois 192.168.2.1

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
script:
  - mvn sonar:sonar  -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=e6ee7d59055a1f6859bb6ddea4a7c6623d969b78 -Dsonar.organization=ozkanpakdil-github
